#!/bin/bash

dataset='cleared_dataset.csv'

bash run_spark.sh datatype datatype_col0 $dataset
bash run_spark.sh datatype datatype_col1 $dataset
bash run_spark.sh datatype datatype_col2 $dataset
bash run_spark.sh datatype datatype_col3 $dataset
bash run_spark.sh datatype datatype_col4 $dataset
bash run_spark.sh datatype datatype_col5 $dataset
bash run_spark.sh datatype datatype_col6 $dataset
bash run_spark.sh datatype datatype_col7 $dataset
bash run_spark.sh datatype datatype_col8 $dataset
bash run_spark.sh datatype datatype_col9 $dataset
bash run_spark.sh datatype datatype_col10 $dataset
bash run_spark.sh datatype datatype_col11 $dataset
bash run_spark.sh datatype datatype_col12 $dataset
bash run_spark.sh datatype datatype_col13 $dataset
bash run_spark.sh datatype datatype_col14 $dataset
bash run_spark.sh datatype datatype_col15 $dataset
bash run_spark.sh datatype datatype_col16 $dataset
bash run_spark.sh datatype datatype_col17 $dataset
bash run_spark.sh datatype datatype_col18 $dataset
bash run_spark.sh datatype datatype_col19 $dataset
bash run_spark.sh datatype datatype_col20 $dataset
bash run_spark.sh datatype datatype_col21 $dataset
bash run_spark.sh datatype datatype_col22 $dataset
bash run_spark.sh datatype datatype_col23 $dataset
